### ISSUE TITLE
Calendar of activities

### ISSUE THREAD

**Issue by firefly-cpp** [AmadejKrepek/sport-data-visualization#14]
We should also provide a charming calendar that shows all activities that one person performed. There should be a week, month, and year view.

**Comment by AmadejKrepek** [comment]
@firefly-cpp I have implemented calendar.
Here is the guideline how to use it.
![calendar](https://user-images.githubusercontent.com/59646470/172648254-9b3126a6-a834-4340-8bc6-3b1c86b6ba9e.gif)

**Comment by firefly-cpp** [comment]
This is amazing! Thanks for all the hard work.
